apiVersion: 1
datasources:
  - name: UiPath metrics
    uid: uipath-metrics
    type: prometheus
    access: proxy
    url: http://thanos-query:9090
    isDefault: true
    jsonData:
      httpMethod: POST
  - name: UiPath logs
    uid: uipath-logs
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
      index: logs-uipath-*
      timeField: '@timestamp'
      logMessageField: message
      logLevelField: log.level
      maxConcurrentShardRequests: 5
      dataLinks:
        - field: trace.id
          url: '${__value.raw}'
          datasourceUid: uipath-traces
  - name: UiPath traces
    uid: uipath-traces
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: uipath-logs
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        filterByTraceID: true
        filterBySpanID: false
